import Navbar from './components/Navbar';
import styles from "@/app/style.module.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body>
        <header className={styles.bdgstick}><Navbar /></header>
        {children}
      </body>
    </html>
  )
}
